### PR TITLE
Create uk.js

### PR DESCRIPTION
**Pull request by PaulFurlet**
Ukrainian language module.
There is apostrophe in STR_ERROR_NETWORK_DISCONNECT, do not know if it must be "shielded" with backslash. Please add it if required.

### CODE REVIEW

**Comment by PFischbeck** [comment]
You will also have to include 'uk' in the `app.json` file.

**Comment by PaulFurlet** [comment]
Already added pull request :)

**Comment by csamsel** [comment]
i guess you should call it ua.js as the iso code uk refers to united kingdom.

**Comment by PaulFurlet** [comment]
No, I have checked it already - UA did not work, UK - switched.
I think because it is language code used, not country.
http://www.science.co.il/Language/Locale-codes.asp

**Pull request merged**
